{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "verdaccio.fullname" . }}
  labels:
    {{- include "verdaccio.labels" . | nindent 4 }}
    {{- with .Values.gatewayApi.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gatewayApi.annotations }}
  annotations:
    {{- include "tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gatewayApi.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.gatewayApi.hostnames }}
  hostnames:
    {{- range .Values.gatewayApi.hostnames }}
    - {{ tpl . $ | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.gatewayApi.rules }}
    {{- toYaml .Values.gatewayApi.rules | nindent 4 }}
    {{- else }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "verdaccio.fullname" . }}
          port: {{ .Values.service.port }}
    {{- end }}
{{- end }}
