{{- if .Values.secretEnvVars }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "verdaccio.fullname" . }}-env
  labels:
    {{- include "verdaccio.labels" . | nindent 4 }}
stringData:
  {{- range $header, $value := .Values.secretEnvVars }}
  {{ printf "%s" (upper (replace "-" "_" $header)) }}: {{ tpl (toString $value) $ }}
  {{- end }}
{{- end }}
