apiVersion: v1
kind: Service
metadata:
  name: {{ template "verdaccio.fullname" . }}
  labels:
    {{- include "verdaccio.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.cachingNginx.enabled }}
      targetPort: caching-nginx
      {{- else }}
      targetPort: http
      {{- end }}
      protocol: TCP
      name: {{ .Values.service.name | default "http"}}
      {{- if contains "NodePort" .Values.service.type }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
    {{- range .Values.extraPorts }}
    - port: {{ .port }}
      {{- if .name }}
      name: {{ .name }}
      {{- end }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "verdaccio.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
